"""add clothes_sekarabng

Revision ID: 6921f9411137
Revises: 6f94dad48316
Create Date: 2025-07-25 09:45:12.610446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6921f9411137'
down_revision = '6f94dad48316'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_progress')
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_module', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('completed_modules', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('last_accessed', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clothe_sekarang', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_user_clothes_set', 'clothes_set', ['clothe_sekarang'], ['id'])

    with op.batch_alter_table('user_artefak', schema=None) as batch_op:
        batch_op.add_column(sa.Column('obtained_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    with op.batch_alter_table('user_clothes_set', schema=None) as batch_op:
        batch_op.add_column(sa.Column('obtained_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    with op.batch_alter_table('user_lencana', schema=None) as batch_op:
        batch_op.add_column(sa.Column('obtained_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_lencana', schema=None) as batch_op:
        batch_op.drop_column('obtained_at')

    with op.batch_alter_table('user_clothes_set', schema=None) as batch_op:
        batch_op.drop_column('obtained_at')

    with op.batch_alter_table('user_artefak', schema=None) as batch_op:
        batch_op.drop_column('obtained_at')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_clothes_set', type_='foreignkey')
        batch_op.drop_column('clothe_sekarang')

    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('last_accessed')
        batch_op.drop_column('completed_modules')
        batch_op.drop_column('current_module')

    op.create_table('_alembic_tmp_progress',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('section', sa.INTEGER(), nullable=False),
    sa.Column('level', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('current_module', sa.VARCHAR(length=100), nullable=True),
    sa.Column('completed_modules', sa.TEXT(), nullable=True),
    sa.Column('last_accessed', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
