"""add harga

Revision ID: 8f015dc976fe
Revises: 
Create Date: 2025-07-25 08:34:29.557788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f015dc976fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artefak', schema=None) as batch_op:
        batch_op.add_column(sa.Column('harga', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artefak', schema=None) as batch_op:
        batch_op.drop_column('harga')

    # ### end Alembic commands ###
